<a href="https://colab.research.google.com/github/wanchenlang-max/Midterm-/blob/main/02_Replication_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import os, shutil, pathlib

REPO_URL = "https://github.com/wanchenlang-max/Midterm-Project-Phase-1.git"
ROOT = "/content/Midterm-Project-Phase-1"

if os.path.exists(ROOT):
    shutil.rmtree(ROOT)

!git clone {REPO_URL} {ROOT}
print("Cloned to:", ROOT)
!find {ROOT} -maxdepth 3 -type d

Cloning into '/content/Midterm-Project-Phase-1'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 52 (delta 11), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (52/52), 73.86 KiB | 1.19 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Cloned to: /content/Midterm-Project-Phase-1
/content/Midterm-Project-Phase-1
/content/Midterm-Project-Phase-1/notebooks
/content/Midterm-Project-Phase-1/data
/content/Midterm-Project-Phase-1/data/processed
/content/Midterm-Project-Phase-1/data/raw
/content/Midterm-Project-Phase-1/.git
/content/Midterm-Project-Phase-1/.git/info
/content/Midterm-Project-Phase-1/.git/logs
/content/Midterm-Project-Phase-1/.git/logs/refs
/content/Midterm-Project-Phase-1/.git/objects
/content/Midterm-Project-Phase-1/.git/objects/info
/content/Midterm-Project-Phase-1/.git/objects/pack
/content/Midterm-Project-Phase-1/.git/refs
/content/Midterm-Project-Phase-1/.git/refs/tags
/content/Midterm-Project-Phase-1/.git/refs/heads
/content/Midterm-Project-Phase-1/.git/refs/remotes
/content/Midterm-Project-Phase-1/.git/branches
/content/Midterm-Project-Phase-1/.git/hooks

In [23]:
import pandas as pd
from pathlib import Path

DATA_PROCESSED = Path(ROOT) / "data" / "processed" / "njmin_public_processed.csv"
df = pd.read_csv(DATA_PROCESSED)
print("Loaded:", DATA_PROCESSED)
print("Shape:", df.shape)
print(df.columns[:20].tolist())

Loaded: /content/Midterm-Project-Phase-1/data/processed/njmin_public_processed.csv
Shape: (410, 46)
['var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17', 'var_18', 'var_19']

In [24]:
print(df.columns.tolist())
df.head(3)

['var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17', 'var_18', 'var_19', 'var_20', 'var_21', 'var_22', 'var_23', 'var_24', 'var_25', 'var_26', 'var_27', 'var_28', 'var_29', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_36', 'var_37', 'var_38', 'var_39', 'var_40', 'var_41', 'var_42', 'var_43', 'var_44', 'var_45']

,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,...,var_36,var_37,var_38,var_39,var_40,var_41,var_42,var_43,var_44,var_45
0,46,1,0,0,0,0,0,1,0,0,...,0.08,1,2,6.50,16.50,1.03,.,0.94,4,4
1,49,2,0,0,0,0,0,1,0,0,...,0.05,0,2,10.00,13.00,1.01,0.89,2.35,4,4
2,506,2,1,0,0,0,0,1,0,0,...,0.25,.,1,11.00,11.00,0.95,0.74,2.33,4,3

In [25]:
from pathlib import Path

sas_path = Path(ROOT) / "data" / "raw" / "check.sas"
dat_path = Path(ROOT) / "data" / "raw" / "public.dat"

print("SAS exists?", sas_path.exists(), sas_path)
print("DAT exists?", dat_path.exists(), dat_path)

SAS exists? True /content/Midterm-Project-Phase-1/data/raw/check.sas
DAT exists? True /content/Midterm-Project-Phase-1/data/raw/public.dat

In [40]:
import re
import pandas as pd

from pathlib import Path
from pathlib import Path

sas_path = Path("/content/Midterm-Project-Phase-1/data/raw/check.sas")

print(sas_path.read_text()[:1500])

print(sas_path.exists())


pattern = re.compile(r"@(\d+)\s+([A-Za-z_]\w*)\s+(\$?[A-Za-z0-9\.]+)", re.MULTILINE)

items = []
for start, name, fmt in pattern.findall(sas_text):
    items.append((int(start), name, fmt))

items = sorted(items, key=lambda x: x[0])

print("Parsed fields:", len(items))
print(items[:10])

COMMENT CHECK PROGRAM TO INPUT DATA AND CHECK;

CMS FI IN DISK FLAT DATA C ;
TITLE1 'INPUT FLAT DATA FILE OF NJ-PA DATA AND CHECK';
DATA CHECK;
INFILE IN;
inPUT SHEET
    CHAINr
    CO_OWNED
    STATEr
    SOUTHJ
    CENTRALJ
    NORTHJ
    PA1
    PA2
    SHORE
    NCALLS
    EMPFT
    EMPPT
True
Parsed fields: 0
[]

In [42]:
import re
from pathlib import Path

sas_path = Path("/content/Midterm-Project-Phase-1/data/raw/check.sas")
sas_text = sas_path.read_text(errors="ignore")

no_strings = re.sub(r"'([^']|'')*'", "''", sas_text)
no_strings = re.sub(r'"([^"]|"")*"', '""', no_strings)

no_strings = re.sub(r"(?is)\bcomment\b.*?;", "", no_strings)
no_strings = re.sub(r"(?is)\bdata\b.*?;", "", no_strings)
m = re.search(r"(?is)\binput\b\s+(.*?);", no_strings)
assert m, "NOT FOUND INPUT ... ）"

block = m.group(1)


block = re.sub(r"@\d+", " ", block)
block = re.sub(r":[A-Za-z0-9.]+", " ", block)
block = re.sub(r"\$[A-Za-z0-9.]+", " ", block)
block = re.sub(r"[;]", " ", block)

names = [x for x in re.split(r"\s+", block.strip()) if x]

print("Number of variables:", len(names))
print("The top 20:", names[:20])
print("The last 20:", names[-20:])

Number of variables: 46
The top 20: ['SHEET', 'CHAINr', 'CO_OWNED', 'STATEr', 'SOUTHJ', 'CENTRALJ', 'NORTHJ', 'PA1', 'PA2', 'SHORE', 'NCALLS', 'EMPFT', 'EMPPT', 'NMGRS', 'WAGE_ST', 'INCTIME', 'FIRSTINC', 'BONUS', 'PCTAFF', 'MEAL']
The last 20: ['NREGS11', 'TYPE2', 'STATUS2', 'DATE2', 'NCALLS2', 'EMPFT2', 'EMPPT2', 'NMGRS2', 'WAGE_ST2', 'INCTIME2', 'FIRSTIN2', 'SPECIAL2', 'MEALS2', 'OPEN2R', 'HRSOPEN2', 'PSODA2', 'PFRY2', 'PENTREE2', 'NREGS2', 'NREGS112']

In [45]:
print("df columns:", len(df.columns))
print("names:", len(names))
assert len(df.columns) == len(names), "Columns do not match"

df columns: 46
names: 46

In [46]:
df.columns = names
df.head()

,SHEET,CHAINr,CO_OWNED,STATEr,SOUTHJ,CENTRALJ,NORTHJ,PA1,PA2,SHORE,...,FIRSTIN2,SPECIAL2,MEALS2,OPEN2R,HRSOPEN2,PSODA2,PFRY2,PENTREE2,NREGS2,NREGS112
0,46,1,0,0,0,0,0,1,0,0,...,0.08,1,2,6.50,16.50,1.03,.,0.94,4,4
1,49,2,0,0,0,0,0,1,0,0,...,0.05,0,2,10.00,13.00,1.01,0.89,2.35,4,4
2,506,2,1,0,0,0,0,1,0,0,...,0.25,.,1,11.00,11.00,0.95,0.74,2.33,4,3
3,56,4,1,0,0,0,0,1,0,0,...,0.15,0,2,10.00,12.00,0.92,0.79,0.87,2,2
4,61,4,1,0,0,0,0,1,0,0,...,0.15,0,2,10.00,12.00,1.01,0.84,0.95,2,2

In [48]:
df[['STATEr','PA1','PA2','EMPFT','EMPPT','NCALLS','WAGE_ST']].head()

   STATEr  PA1  PA2  EMPFT  EMPPT  NCALLS WAGE_ST
0       0    1    0  30.00  15.00       0       .
1       0    1    0   6.50   6.50       0       .
2       0    1    0   3.00   7.00       0       .
3       0    1    0  20.00  20.00       0    5.00
4       0    1    0   6.00  26.00       0    5.50

In [49]:
df['is_pa'] = ((df['PA1'] == 1) | (df['PA2'] == 1)).astype(int)
df['treat'] = (1 - df['is_pa'])   # NJ = treatment
df[['PA1','PA2','is_pa','treat']].head()

   PA1  PA2  is_pa  treat
0    1    0      1      0
1    1    0      1      0
2    1    0      1      0
3    1    0      1      0
4    1    0      1      0

In [50]:
df['treat'].value_counts()
df['is_pa'].value_counts()

is_pa
0    331
1     79
Name: count, dtype: int64

In [51]:
[c for c in df.columns if c.endswith('2')][:80]

['PA2',
 'TYPE2',
 'STATUS2',
 'DATE2',
 'NCALLS2',
 'EMPFT2',
 'EMPPT2',
 'NMGRS2',
 'WAGE_ST2',
 'INCTIME2',
 'FIRSTIN2',
 'SPECIAL2',
 'MEALS2',
 'HRSOPEN2',
 'PSODA2',
 'PFRY2',
 'PENTREE2',
 'NREGS2',
 'NREGS112']

In [52]:
needed = ['EMPFT2','EMPPT2','NCALLS2','WAGE_ST2']
print({k: (k in df.columns) for k in needed})

{'EMPFT2': True, 'EMPPT2': True, 'NCALLS2': True, 'WAGE_ST2': True}

In [53]:
import numpy as np
df['WAGE_ST'] = pd.to_numeric(df['WAGE_ST'], errors='coerce')

In [54]:
print(df['treat'].value_counts())
print([c for c in df.columns if c.endswith('2')][:40])

treat
1    331
0     79
Name: count, dtype: int64
['PA2', 'TYPE2', 'STATUS2', 'DATE2', 'NCALLS2', 'EMPFT2', 'EMPPT2', 'NMGRS2', 'WAGE_ST2', 'INCTIME2', 'FIRSTIN2', 'SPECIAL2', 'MEALS2', 'HRSOPEN2', 'PSODA2', 'PFRY2', 'PENTREE2', 'NREGS2', 'NREGS112']

In [55]:
[c for c in df.columns if "DATE" in c.upper() or c.endswith("1") or c.endswith("2")][:50]

['PA1',
 'PA2',
 'NREGS11',
 'TYPE2',
 'STATUS2',
 'DATE2',
 'NCALLS2',
 'EMPFT2',
 'EMPPT2',
 'NMGRS2',
 'WAGE_ST2',
 'INCTIME2',
 'FIRSTIN2',
 'SPECIAL2',
 'MEALS2',
 'HRSOPEN2',
 'PSODA2',
 'PFRY2',
 'PENTREE2',
 'NREGS2',
 'NREGS112']

In [73]:
import numpy as np
import pandas as pd

id_cols = ['SHEET']
date_cols = []
df['EMPFT'] = pd.to_numeric(df['EMPFT'], errors='coerce')
df['EMPPT'] = pd.to_numeric(df['EMPPT'], errors='coerce')
df['EMPFT2'] = pd.to_numeric(df['EMPFT2'], errors='coerce')
df['EMPPT2'] = pd.to_numeric(df['EMPPT2'], errors='coerce')


df['fte1'] = df['EMPFT'] + 0.5*df['EMPPT']
df['fte2'] = df['EMPFT2'] + 0.5*df['EMPPT2']

long = pd.DataFrame({
    'SHEET': pd.concat([df['SHEET'], df['SHEET']], ignore_index=True),
    'treat': pd.concat([df['treat'], df['treat']], ignore_index=True),
    'fte': pd.concat([df['fte1'], df['fte2']], ignore_index=True),
    'post': np.repeat([0,1], repeats=len(df))
})
long['did'] = long['treat'] * long['post']
long.head()

   SHEET  treat    fte  post  did
0     46      0  37.50     0    0
1     49      0   9.75     0    0
2    506      0   6.50     0    0
3     56      0  30.00     0    0
4     61      0  19.00     0    0

In [59]:
long.groupby(['treat','post'])['fte'].mean()

treat  post
0      0       19.948718
       1       17.542208
1      0       17.065184
       1       17.572656
Name: fte, dtype: float64

In [74]:
import statsmodels.formula.api as smf

long_filtered = long.dropna(subset=['fte', 'treat', 'post', 'did'])

model = smf.ols("fte ~ treat + post + did", data=long_filtered)

res_ols = model.fit()

filtered_groups = long_filtered["SHEET"]

res = res_ols.get_robustcov_results(cov_type="cluster", groups=filtered_groups)
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    fte   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.891
Date:                Fri, 27 Feb 2026   Prob (F-statistic):              0.130
Time:                        23:00:50   Log-Likelihood:                -2894.8
No. Observations:                 801   AIC:                             5798.
Df Residuals:                     797   BIC:                             5816.
Df Model:                           3
Covariance Type:              cluster
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     19.9487      1.318     15.135      0.000      17.358      22.540
treat         -2.8835      1.402     -2.057      0.040      -5.639      -0.128
post          -2.4065      1.207     -1.994      0.047      -4.779      -0.034
did            2.9140      1.291      2.256      0.025       0.375       5.453
==============================================================================
Omnibus:                      245.537   Durbin-Watson:                   1.845
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              985.101
Skew:                           1.388   Prob(JB):                    1.22e-214
Kurtosis:                       7.670   Cond. No.                         11.3
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [75]:
import numpy as np
import pandas as pd

num_cols = [
    'EMPFT','EMPPT','NCALLS','WAGE_ST',
    'EMPFT2','EMPPT2','NCALLS2','WAGE_ST2'
]

for c in num_cols:
    df[c] = pd.to_numeric(df[c], errors='coerce')  # '.' -> NaN

df[num_cols].isna().mean().sort_values(ascending=False)

NCALLS2     0.607317
WAGE_ST2    0.051220
WAGE_ST     0.048780
EMPFT2      0.029268
EMPPT2      0.024390
EMPFT       0.014634
EMPPT       0.009756
NCALLS      0.000000
dtype: float64

In [76]:
df['fte1'] = df['EMPFT']  + 0.5 * df['EMPPT']
df['fte2'] = df['EMPFT2'] + 0.5 * df['EMPPT2']

df[['EMPFT','EMPPT','fte1','EMPFT2','EMPPT2','fte2']].head()

   EMPFT  EMPPT   fte1  EMPFT2  EMPPT2  fte2
0   30.0   15.0  37.50     3.5    35.0  21.0
1    6.5    6.5   9.75     0.0    15.0   7.5
2    3.0    7.0   6.50     3.0     7.0   6.5
3   20.0   20.0  30.00     0.0    36.0  18.0
4    6.0   26.0  19.00    28.0     3.0  29.5

In [77]:
id_col = 'SHEET'

df_long = pd.DataFrame({
    id_col: pd.concat([df[id_col], df[id_col]], ignore_index=True),
    'treat': pd.concat([df['treat'], df['treat']], ignore_index=True),
    'post':  pd.Series([0]*len(df) + [1]*len(df)),
    'fte':   pd.concat([df['fte1'], df['fte2']], ignore_index=True),
    'wage':  pd.concat([df['WAGE_ST'], df['WAGE_ST2']], ignore_index=True),
    'ncalls':pd.concat([df['NCALLS'], df['NCALLS2']], ignore_index=True),
})
df_long.head()

   SHEET  treat  post    fte  wage  ncalls
0     46      0     0  37.50   NaN     0.0
1     49      0     0   9.75   NaN     0.0
2    506      0     0   6.50   NaN     0.0
3     56      0     0  30.00   5.0     0.0
4     61      0     0  19.00   5.5     0.0

In [78]:
df_long.groupby(['treat','post'])['fte'].mean()

treat  post
0      0       19.948718
       1       17.542208
1      0       17.065184
       1       17.572656
Name: fte, dtype: float64

In [79]:
means = df_long.groupby(['treat','post'])['fte'].mean().unstack()
means.columns = ['pre','post']
means['diff_post-pre'] = means['post'] - means['pre']
means

             pre       post  diff_post-pre
treat
0      19.948718  17.542208      -2.406510
1      17.065184  17.572656       0.507472

In [80]:
did_manual = (means.loc[1,'diff_post-pre'] - means.loc[0,'diff_post-pre'])
did_manual

np.float64(2.9139823574304025)

In [81]:
import statsmodels.formula.api as smf

reg_df = df_long.dropna(subset=['fte', 'treat', 'post', id_col]).copy()

m = smf.ols('fte ~ treat * post', data=reg_df)
res = m.fit(cov_type='cluster', cov_kwds={'groups': reg_df[id_col]})

print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    fte   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.891
Date:                Fri, 27 Feb 2026   Prob (F-statistic):              0.130
Time:                        23:12:27   Log-Likelihood:                -2894.8
No. Observations:                 801   AIC:                             5798.
Df Residuals:                     797   BIC:                             5816.
Df Model:                           3
Covariance Type:              cluster
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     19.9487      1.318     15.135      0.000      17.365      22.532
treat         -2.8835      1.402     -2.057      0.040      -5.631      -0.136
post          -2.4065      1.207     -1.994      0.046      -4.772      -0.041
treat:post     2.9140      1.291      2.256      0.024       0.383       5.445
==============================================================================
Omnibus:                      245.537   Durbin-Watson:                   1.845
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              985.101
Skew:                           1.388   Prob(JB):                    1.22e-214
Kurtosis:                       7.670   Cond. No.                         11.3
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [82]:
print("Manual DID:", did_manual)
print("Regression DID (treat:post):", res.params['treat:post'])

Manual DID: 2.9139823574304025
Regression DID (treat:post): 2.913982357430467

In [83]:
out = pd.DataFrame({
    'coef': res.params,
    'se_cluster': res.bse,
    't': res.tvalues,
    'p': res.pvalues
})
out.loc[['Intercept','treat','post','treat:post']]

                 coef  se_cluster          t             p
Intercept   19.948718    1.318071  15.134781  9.549758e-52
treat       -2.883534    1.401798  -2.057025  3.968380e-02
post        -2.406510    1.207109  -1.993615  4.619413e-02
treat:post   2.913982    1.291448   2.256368  2.404757e-02